const sampleListings = [
  {
    title: "Tokyo Minimalist Studio",
    description: "Modern minimalist studio in central Tokyo with compact luxury and smart-home features.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?auto=format&fit=crop&w=800&q=60",
    },
    price: 1900,
    location: "Tokyo",
    country: "Japan",
    categories: ["Rooms", "Iconic Cities", "Trending"],
  },
  {
    title: "Queenstown Lake Cabin",
    description: "Peaceful wooden cabin by the lake with mountain reflections and quiet surroundings.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2100,
    location: "Queenstown",
    country: "New Zealand",
    categories: ["Camping", "Hill Stations"],
  },
  {
    title: "Santorini Sunset Villa",
    description: "Cliffside villa with private pool and unforgettable sunset views over the sea.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=60",
    },
    price: 5200,
    location: "Santorini",
    country: "Greece",
    categories: ["Amazing Pools", "Islands", "Trending"],
  },
  {
    title: "Zermatt Snow Chalet",
    description: "Warm alpine chalet near snowy slopes with a fireplace and mountain air.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=60",
    },
    price: 3900,
    location: "Zermatt",
    country: "Switzerland",
    categories: ["Hill Stations", "Camping"],
  },
  {
    title: "Dubai Marina Sky Loft",
    description: "High-rise luxury loft with skyline views and premium city living.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    },
    price: 4300,
    location: "Dubai",
    country: "UAE",
    categories: ["Iconic Cities", "Rooms"],
  },
  {
    title: "Bali Rainforest Pool Villa",
    description: "Private villa surrounded by tropical greenery and a peaceful infinity pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=60",
    },
    price: 3100,
    location: "Ubud",
    country: "Indonesia",
    categories: ["Amazing Pools", "Islands", "Trending"],
  },
  {
    title: "Maldives Lagoon Bungalow",
    description: "Overwater bungalow with glass-clear water and direct access to the lagoon.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=800&q=60",
    },
    price: 7500,
    location: "Maldives",
    country: "Maldives",
    categories: ["Islands", "Trending"],
  },
  {
    title: "Paris Balcony Suite",
    description: "Elegant Paris stay with classic interiors and charming balcony views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=60",
    },
    price: 2600,
    location: "Paris",
    country: "France",
    categories: ["Iconic Cities", "Rooms"],
  },
  {
    title: "Iceland Lava Cabin",
    description: "Dark modern cabin set against dramatic volcanic terrain and moody skies.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 2900,
    location: "Vik",
    country: "Iceland",
    categories: ["Camping", "Hill Stations"],
  },
  {
    title: "Marrakech Mosaic Riad",
    description: "Traditional riad with intricate tiles, courtyard charm, and rooftop comfort.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=60",
    },
    price: 2400,
    location: "Marrakech",
    country: "Morocco",
    categories: ["Architect", "Trending"],
  },
  {
    title: "Venice Canal View Loft",
    description: "Romantic loft overlooking a quiet canal in old Venice.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60",
    },
    price: 2800,
    location: "Venice",
    country: "Italy",
    categories: ["Iconic Cities", "Rooms"],
  },
  {
    title: "Lucerne Lakeside Chalet",
    description: "Charming chalet with calm lake access and alpine beauty all around.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=60",
    },
    price: 3100,
    location: "Lucerne",
    country: "Switzerland",
    categories: ["Hill Stations", "Camping"],
  },
  {
    title: "Malibu Oceanfront House",
    description: "Stylish beach house with open interiors and dramatic Pacific views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
    },
    price: 5200,
    location: "Malibu",
    country: "United States",
    categories: ["Trending", "Amazing Pools"],
  },
  {
    title: "Barcelona Heritage Flat",
    description: "Historic city apartment near the Gothic Quarter with old-world appeal.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Barcelona",
    country: "Spain",
    categories: ["Iconic Cities", "Rooms"],
  },
  {
    title: "Sahara Moonlight Camp",
    description: "Luxury desert tent stay with dune views and unforgettable stargazing.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Merzouga",
    country: "Morocco",
    categories: ["Camping", "Trending"],
  },
  {
    title: "Toronto Glass Condo",
    description: "Modern downtown condo with skyline windows and comfortable city access.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    },
    price: 2100,
    location: "Toronto",
    country: "Canada",
    categories: ["Rooms", "Iconic Cities"],
  },
  {
    title: "Phuket Sea Breeze Suite",
    description: "Ocean-facing suite with private plunge pool and tropical scenery.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?auto=format&fit=crop&w=800&q=60",
    },
    price: 3600,
    location: "Phuket",
    country: "Thailand",
    categories: ["Amazing Pools", "Islands"],
  },
  {
    title: "Seoul Han River Stay",
    description: "Sleek apartment with river views and stylish urban comfort.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Seoul",
    country: "South Korea",
    categories: ["Rooms", "Iconic Cities"],
  },
  {
    title: "Cape Town Cliff Retreat",
    description: "Modern villa perched above the coast with dramatic ocean scenery.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1494522358652-f30e61a60313?auto=format&fit=crop&w=800&q=60",
    },
    price: 3900,
    location: "Cape Town",
    country: "South Africa",
    categories: ["Trending", "Amazing Pools"],
  },
  {
    title: "Provence Lavender Farmhouse",
    description: "Stone farmhouse surrounded by lavender fields and rural calm.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1599423300746-b62533397364?auto=format&fit=crop&w=800&q=60",
    },
    price: 3300,
    location: "Provence",
    country: "France",
    categories: ["Farms", "Trending"],
  },
  {
    title: "Kyoto Zen Garden Home",
    description: "Traditional house with tatami charm and a peaceful private garden.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Kyoto",
    country: "Japan",
    categories: ["Rooms", "Architect"],
  },
  {
    title: "Patagonia Glacier Cabin",
    description: "Remote wooden cabin with glacier views and rugged natural beauty.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Patagonia",
    country: "Argentina",
    categories: ["Camping", "Hill Stations"],
  },
  {
    title: "New York Central Loft",
    description: "Luxury loft near Central Park with open interiors and city energy.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=60",
    },
    price: 4100,
    location: "New York",
    country: "United States",
    categories: ["Iconic Cities", "Rooms", "Trending"],
  },
  {
    title: "Udaipur Palace Courtyard Stay",
    description: "Royal-style heritage stay with arches, lake breeze, and elegant decor.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
    },
    price: 3500,
    location: "Udaipur",
    country: "India",
    categories: ["Castles", "Architect", "Trending"],
  },
  {
    title: "Goa Floating Houseboat",
    description: "Fun waterfront stay with sea breeze, deck seating, and sunset views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2300,
    location: "Goa",
    country: "India",
    categories: ["Boats", "Islands", "Trending"],
  },
  {
    title: "Manali Pine Cottage",
    description: "Mountain cottage among pine forests with a peaceful valley setting.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Manali",
    country: "India",
    categories: ["Hill Stations", "Rooms"],
  },
  {
    title: "Jaipur Haveli Residence",
    description: "Traditional haveli-style residence with carved doors and colorful courtyards.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=800&q=60",
    },
    price: 2700,
    location: "Jaipur",
    country: "India",
    categories: ["Architect", "Castles"],
  },
  {
    title: "Kerala Backwater Cruiser",
    description: "Private backwater boat stay with serene river routes and local meals.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Alleppey",
    country: "India",
    categories: ["Boats", "Trending"],
  },
  {
    title: "Mysore Royal Room",
    description: "Heritage room inspired by regal interiors and antique South Indian charm.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 2400,
    location: "Mysore",
    country: "India",
    categories: ["Castles", "Rooms"],
  },
  {
    title: "Coorg Coffee Estate Retreat",
    description: "Relaxing plantation stay surrounded by coffee plants and misty greenery.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Coorg",
    country: "India",
    categories: ["Farms", "Hill Stations"],
  },
  {
    title: "Andaman Bamboo Beach Hut",
    description: "Simple island hut close to the beach with palms and turquoise water.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=800&q=60",
    },
    price: 2600,
    location: "Andaman",
    country: "India",
    categories: ["Islands", "Rooms"],
  },
  {
    title: "Leh Starlight Dome Camp",
    description: "Dome stay under brilliant skies in a high-altitude mountain desert.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=800&q=60",
    },
    price: 2800,
    location: "Leh",
    country: "India",
    categories: ["Domes", "Camping", "Hill Stations"],
  },
  {
    title: "Mumbai Marine Studio",
    description: "Compact urban studio near the coast with modern interiors and city access.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=60",
    },
    price: 2900,
    location: "Mumbai",
    country: "India",
    categories: ["Iconic Cities", "Rooms", "Trending"],
  },
  {
    title: "Amsterdam Canal House",
    description: "Cozy canal-side stay with classic European charm and walkable streets.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Amsterdam",
    country: "Netherlands",
    categories: ["Iconic Cities", "Rooms"],
  },
  {
    title: "Cappadocia Cave Dome",
    description: "Unique cave-style dome stay with sunrise balloon views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    },
    price: 3400,
    location: "Cappadocia",
    country: "Turkey",
    categories: ["Domes", "Architect", "Trending"],
  },
  {
    title: "Prague Castle View Flat",
    description: "Historic flat with postcard-worthy castle views and old town access.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=60",
    },
    price: 2550,
    location: "Prague",
    country: "Czech Republic",
    categories: ["Castles", "Iconic Cities", "Rooms"],
  },
  {
    title: "Tuscany Vineyard Farm Stay",
    description: "Warm countryside farmhouse near vineyards and rolling green hills.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=60",
    },
    price: 3350,
    location: "Tuscany",
    country: "Italy",
    categories: ["Farms", "Trending"],
  },
  {
    title: "Oslo Fjord Cabin",
    description: "Scandinavian wooden cabin with quiet water views and clean interiors.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464890100898-a385f744067f?auto=format&fit=crop&w=800&q=60",
    },
    price: 2750,
    location: "Oslo",
    country: "Norway",
    categories: ["Camping", "Hill Stations"],
  },
  {
    title: "Sydney Harbour Apartment",
    description: "Stylish apartment near the harbour with bright rooms and iconic surroundings.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505692952047-1a78307da8f2?auto=format&fit=crop&w=800&q=60",
    },
    price: 3650,
    location: "Sydney",
    country: "Australia",
    categories: ["Iconic Cities", "Rooms", "Trending"],
  },
  {
    title: "Banff Timber Lodge",
    description: "Rustic timber lodge with snowy peaks, pine forests, and quiet mornings.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=60",
    },
    price: 3250,
    location: "Banff",
    country: "Canada",
    categories: ["Hill Stations", "Camping"],
  },
  {
    title: "Lisbon Tramside Loft",
    description: "Chic loft in Lisbon with colorful streets and old-city atmosphere nearby.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 2450,
    location: "Lisbon",
    country: "Portugal",
    categories: ["Iconic Cities", "Rooms"],
  },
  {
    title: "Edinburgh Stone Castle Stay",
    description: "Atmospheric stay with old stone details and a historic Scottish feel.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1519642918688-7e43b19245d8?auto=format&fit=crop&w=800&q=60",
    },
    price: 2950,
    location: "Edinburgh",
    country: "Scotland",
    categories: ["Castles", "Rooms", "Trending"],
  },
  {
    title: "Bora Bora Water Villa",
    description: "Luxury villa over tropical blue water with direct sea access and privacy.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505881502353-a1986add3762?auto=format&fit=crop&w=800&q=60",
    },
    price: 8200,
    location: "Bora Bora",
    country: "French Polynesia",
    categories: ["Islands", "Amazing Pools", "Trending"],
  },
  {
    title: "Rishikesh Riverside Camp",
    description: "Relaxed riverside camp with mountain air and bonfire evenings.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Rishikesh",
    country: "India",
    categories: ["Camping", "Hill Stations"],
  },
  {
    title: "Ladakh Stone House",
    description: "Traditional mountain home with rugged views and simple local comfort.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
    },
    price: 2100,
    location: "Nubra Valley",
    country: "India",
    categories: ["Hill Stations", "Rooms"],
  },
  {
    title: "Stockholm Archipelago Cottage",
    description: "Bright Nordic cottage by the water with clean design and quiet scenery.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 2850,
    location: "Stockholm",
    country: "Sweden",
    categories: ["Rooms", "Islands"],
  },
  {
    title: "Doha Pearl Residence",
    description: "Upscale residence with elegant interiors and premium city amenities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=800&q=60",
    },
    price: 3750,
    location: "Doha",
    country: "Qatar",
    categories: ["Rooms", "Iconic Cities"],
  },
  {
    title: "Lake Bled Castle Cottage",
    description: "Romantic cottage near the lake with postcard views and quiet evenings.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    },
    price: 3150,
    location: "Bled",
    country: "Slovenia",
    categories: ["Castles", "Hill Stations", "Trending"],
  },
  {
    title: "Munnar Tea Valley Cabin",
    description: "Serene cabin surrounded by tea gardens and cool green hills.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=60",
    },
    price: 1850,
    location: "Munnar",
    country: "India",
    categories: ["Hill Stations", "Farms"],
  },
  {
    title: "Crete Whitewashed Villa",
    description: "Bright Mediterranean villa with sea air, open terraces, and summer charm.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=60",
    },
    price: 4450,
    location: "Crete",
    country: "Greece",
    categories: ["Islands", "Amazing Pools"],
  },
  {
    title: "Budapest Riverside Apartment",
    description: "Comfortable apartment near the river with classic European city character.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=60",
    },
    price: 2350,
    location: "Budapest",
    country: "Hungary",
    categories: ["Iconic Cities", "Rooms"],
  },
  {
    title: "Kashmir Houseboat Escape",
    description: "Traditional houseboat stay with wooden interiors and peaceful lake mornings.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=800&q=60",
    },
    price: 2650,
    location: "Srinagar",
    country: "India",
    categories: ["Boats", "Hill Stations", "Trending"],
  },
  {
    title: "Bavarian Forest Lodge",
    description: "Warm forest lodge with rustic details and scenic countryside silence.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=60",
    },
    price: 2550,
    location: "Bavaria",
    country: "Germany",
    categories: ["Camping", "Hill Stations"],
  },
  {
    title: "Muscat Courtyard Villa",
    description: "Elegant villa with open courtyard design and a warm desert-sea vibe.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
    },
    price: 3550,
    location: "Muscat",
    country: "Oman",
    categories: ["Architect", "Amazing Pools"],
  },
  {
    title: "Hanoi Old Quarter Home",
    description: "Charming city home with cozy interiors in a vibrant historic neighborhood.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1750,
    location: "Hanoi",
    country: "Vietnam",
    categories: ["Iconic Cities", "Rooms"],
  },
  {
    title: "Lake District Stone Barn",
    description: "Converted barn with stone walls, green hills, and peaceful countryside stays.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464146072230-91cabc968266?auto=format&fit=crop&w=800&q=60",
    },
    price: 2450,
    location: "Cumbria",
    country: "United Kingdom",
    categories: ["Farms", "Hill Stations"],
  },
  {
    title: "Sicily Coastal Pool House",
    description: "Sunny coastal home with poolside comfort and Mediterranean views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
    },
    price: 4200,
    location: "Sicily",
    country: "Italy",
    categories: ["Amazing Pools", "Islands", "Trending"],
  },
];

module.exports = { data: sampleListings };